### ISSUE TITLE
Adding a server via a domain name doesn't work as expected. 

### ISSUE THREAD

**Issue by HoroshoVse** [ZanborPanel/ZanborPanel#2]
When attempting to add a server using a link like https://domain.com/, it doesn't succeed. If the server IP is provided in the format, for example, http://ip:443/ or [https://IP:443](https://ip/), the system prompts for a login and password. However, in the end, an error occurs along with a list of potential issues.

**Comment by ZanborPanel** [comment]
Hello, good time, this problem is solved in the latest version of the robot, use the latest version of the robot.
