### ISSUE TITLE
مشکل نصب

### ISSUE THREAD

**Issue by Amirnikoo66** [ZanborPanel/ZanborPanel#3]
من از بستلا هاست گرفتم
طبق توضیح دیتابیس و … انجام دادم
موقع ورود اطلاعات
خطای “توکن ارسالی اشتباه است” میگیرم
توکن رو هم از بات فادر میگیرم

**Comment by ZanborPanel** [comment]
مشکل به کلی حل شده 
از آخرین نسخه ربات استفاده کنید و ورژن هاست رو روی 7.4 قرار بدید
